web:
    image: harry/homestead:v1
    restart: always
    ports:
        - "80:80" # web
        - "22:22" # ssh
        - "35729:35729" # live reload
        - "9876:9876" # karma server
    volumes:
        - ~/.composer:/home/homestead/.composer # composer caching
        - ~/.gitconfig:/home/homestead/.gitconfig # Git configuration ( access alias && config )
        - ~/.ssh:/home/homestead/.ssh # Ssh keys for easy deployment inside the container
        - ~/Dev:/var/www/html # all apps
        - ~/_docker/volumes/sites-available:/etc/nginx/sites-available # nginx sites ( in case you recreate the container )
        - ~/_docker/volumes/sites-enabled:/etc/nginx/sites-enabled # nginx sites ( in case you recreate the container )
    links:
        - mariadb

mariadb:
    image: tutum/mariadb
    restart: always
    ports:
        - "3306:3306"
    environment:
        MARIADB_USER: admin # cannot be changed ( for info. only )
        MARIADB_PASS: root
    volumes:
        - ~/_docker/volumes/mysql:/var/lib/mysql # database files
